force-app/main/default/objects/Round_Robin_Tracker__c/Round_Robin_Tracker__c.object-meta.xml
<CustomObject>
    <label>Round Robin Tracker</label>
    <nameField>
        <displayFormat>ASSIGN-{0000}</displayFormat>
        <label>Round Robin Tracker Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Round Robin Trackers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Round_Robin_Tracker__c/fields/Current_Assignee__c.field-meta.xml
<CustomField>
    <fullName>Current_Assignee__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Current Assignee</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Round_Robin_Trackers</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Round_Robin_Tracker__c/fields/Last_Assigned_Date__c.field-meta.xml
<CustomField>
    <fullName>Last_Assigned_Date__c</fullName>
    <label>Last Assigned Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/classes/OpportunityController.cls
public class OpportunityController {

    public static void AssignOwner(List<Opportunity> Opps) {
        List<Round_Robin_Tracker__c> SARAssignees = [SELECT Current_Assignee__c, Last_Assigned_Date__c
                                                     FROM Round_Robin_Tracker__c
                                                     WHERE Current_Assignee__r.isActive = True 
                                                     ORDER BY Last_Assigned_Date__c ASC, Order__c ASC];

        if (!SARAssignees.isEmpty()) {
            List<Round_Robin_Tracker__c> RRAssigneesToUpdate = new List<Round_Robin_Tracker__c>();
            Integer CSRindex = 0;

            for (Opportunity opp : Opps) {
                Round_Robin_Tracker__c RRAssignee = SARAssignees.get(Math.mod(CSRindex, SARAssignees.size()));
                opp.OwnerId = RRAssignee.Current_Assignee__c;

                RRAssignee.Last_Assigned_Date__c = System.now();

                RRAssigneesToUpdate.add(RRAssignee);
                CSRindex++;
            }

            update RRAssigneesToUpdate;
        }
    }
}